#!/usr/bin/env bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Banner
echo -e "${BLUE}"
echo "  ╔═══════════════════════════════╗"
echo "  ║         Gateway Setup         ║"
echo "  ║   Certificate & Proxy Manager ║"
echo "  ╚═══════════════════════════════╝"
echo -e "${NC}"

# ── Helpers ──────────────────────────────────────────────────────────

log_ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
log_warn() { echo -e "  ${YELLOW}!${NC} $1"; }
log_err()  { echo -e "  ${RED}✗${NC} $1"; }

prompt_with_default() {
  local prompt="$1"
  local default="$2"
  local result
  read -rp "$(echo -e "${YELLOW}${prompt}${NC} [${default}]: ")" result
  echo "${result:-$default}"
}

prompt_secret() {
  local prompt="$1"
  local result
  read -rs -p "$(echo -e "${YELLOW}${prompt}${NC}: ")" result
  echo "" >&2
  echo "$result"
}

prompt_yn() {
  local prompt="$1"
  local default="${2:-y}"
  local result
  read -rp "$(echo -e "${YELLOW}${prompt}${NC} [${default}]: ")" result
  result="${result:-$default}"
  [[ "${result,,}" == "y" || "${result,,}" == "yes" ]]
}

# ── Prerequisites ────────────────────────────────────────────────────

check_prerequisites() {
  echo -e "${GREEN}=== Checking Prerequisites ===${NC}\n"
  local missing=0

  if command -v docker &>/dev/null; then
    log_ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
  else
    log_err "Docker is not installed. Install it from https://docs.docker.com/engine/install/"
    missing=1
  fi

  if docker compose version &>/dev/null; then
    log_ok "Docker Compose $(docker compose version --short 2>/dev/null || echo 'v2')"
  else
    log_err "Docker Compose v2 is required. Install the docker-compose-plugin package."
    missing=1
  fi

  if command -v openssl &>/dev/null; then
    log_ok "OpenSSL $(openssl version 2>/dev/null | awk '{print $2}')"
  else
    log_err "OpenSSL is required to generate security keys."
    missing=1
  fi

  if command -v curl &>/dev/null; then
    log_ok "curl available"
  else
    log_err "curl is required for health checks."
    missing=1
  fi

  if [ $missing -ne 0 ]; then
    echo ""
    log_err "Missing prerequisites. Please install them and re-run this script."
    exit 1
  fi
  echo ""
}

# ── Main ─────────────────────────────────────────────────────────────

main() {
  # Change to the directory where the script lives (project root)
  cd "$(dirname "$0")"

  check_prerequisites

  # Guard against overwriting existing config
  if [ -f .env ]; then
    echo ""
    log_warn "An existing .env file was found."
    if ! prompt_yn "Overwrite it?" "n"; then
      echo "Keeping existing .env. Exiting."
      exit 0
    fi
    echo ""
  fi

  # ── Basic Configuration ──

  echo -e "${GREEN}=== Basic Configuration ===${NC}\n"

  DOMAIN=$(prompt_with_default "Management domain (e.g., gateway.example.com)" "localhost")

  if [ "$DOMAIN" = "localhost" ]; then
    APP_URL="http://localhost:3000"
  else
    APP_URL="https://${DOMAIN}"
  fi

  ACME_EMAIL=$(prompt_with_default "Email for Let's Encrypt certificates" "admin@example.com")

  # ── OIDC Authentication ──

  echo -e "\n${GREEN}=== OIDC Authentication ===${NC}\n"

  OIDC_ISSUER=$(prompt_with_default "OIDC Issuer URL" "https://your-idp.com")
  OIDC_CLIENT_ID=$(prompt_with_default "OIDC Client ID" "gateway")
  OIDC_CLIENT_SECRET=$(prompt_secret "OIDC Client Secret")

  if [ -z "$OIDC_CLIENT_SECRET" ]; then
    log_warn "No client secret entered. You can set OIDC_CLIENT_SECRET in .env later."
  fi

  OIDC_REDIRECT_URI="${APP_URL}/auth/callback"

  # ── Security ──

  echo -e "\n${GREEN}=== Security ===${NC}\n"

  echo "Generating security keys..."
  PKI_MASTER_KEY=$(openssl rand -hex 32)
  SESSION_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  log_ok "PKI Master Key generated"
  log_ok "Session Secret generated"
  log_ok "Database Password generated"

  # ── ACME staging ──

  echo ""
  if [ "$DOMAIN" = "localhost" ]; then
    ACME_STAGING="true"
    log_warn "ACME staging enabled automatically for localhost."
  else
    ACME_STAGING=$(prompt_with_default "Use Let's Encrypt staging? (recommended for first deploy)" "true")
  fi

  # ── Write .env ──

  echo -e "\n${GREEN}=== Generating Configuration ===${NC}\n"

  cat > .env << ENVEOF
# Gateway Configuration -- Generated by install.sh
# $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Server
PORT=3000
NODE_ENV=production
APP_URL=${APP_URL}

# Database
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgres://gateway:${DB_PASSWORD}@postgres:5432/gateway

# Redis
REDIS_URL=redis://redis:6379

# OIDC Authentication
OIDC_ISSUER=${OIDC_ISSUER}
OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI}
OIDC_SCOPES=openid email profile

# Session
SESSION_SECRET=${SESSION_SECRET}
SESSION_EXPIRY=2592000

# PKI Master Key (DO NOT CHANGE after initial setup)
PKI_MASTER_KEY=${PKI_MASTER_KEY}

# ACME / Let's Encrypt
ACME_EMAIL=${ACME_EMAIL}
ACME_STAGING=${ACME_STAGING}

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=5000

# PKI Defaults
DEFAULT_CRL_VALIDITY_HOURS=24
DEFAULT_OCSP_VALIDITY_MINUTES=60
EXPIRY_WARNING_DAYS=30
EXPIRY_CRITICAL_DAYS=7

# Background Jobs
HEALTH_CHECK_INTERVAL_SECONDS=30
ACME_RENEWAL_CRON=0 3 * * *
EXPIRY_CHECK_CRON=0 6 * * *
ENVEOF

  log_ok ".env file created"

  # Create necessary directories
  mkdir -p nginx/html

  log_ok "Directories verified"

  # ── Start Services ──

  echo -e "\n${GREEN}=== Starting Services ===${NC}\n"

  echo "Pulling Docker images..."
  docker compose pull 2>&1 | tail -1 || true

  echo "Building application image..."
  docker compose build app 2>&1 | tail -1

  echo "Starting services..."
  docker compose up -d

  echo ""
  echo "Waiting for services to become healthy..."
  local retries=30
  while [ $retries -gt 0 ]; do
    if docker compose exec -T app wget -qO- http://localhost:3000/health > /dev/null 2>&1; then
      break
    fi
    retries=$((retries - 1))
    printf "."
    sleep 2
  done
  echo ""

  if [ $retries -eq 0 ]; then
    echo ""
    log_err "Services did not become healthy within 60 seconds."
    echo "  Check logs with:  docker compose logs"
    echo "  Retry with:       docker compose up -d"
    exit 1
  fi

  log_ok "All services are healthy"

  # ── Done ──

  echo ""
  echo -e "${GREEN}════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Gateway is running!${NC}"
  echo -e "${GREEN}════════════════════════════════════════${NC}"
  echo ""
  echo -e "  Management UI:  ${BLUE}${APP_URL}${NC}"
  echo -e "  API Docs:       ${BLUE}${APP_URL}/docs${NC}"
  echo ""
  echo -e "  Proxy ports:    80 (HTTP), 443 (HTTPS)"
  echo ""
  echo -e "${YELLOW}Important:${NC}"
  echo "  - PKI Master Key is stored in .env -- back it up securely!"
  echo "  - First user to log in via OIDC gets the 'viewer' role."
  echo "  - Promote to admin:"
  echo "      docker compose exec postgres psql -U gateway -c \\"
  echo "        \"UPDATE users SET role='admin' WHERE email='you@example.com';\""
  echo ""
}

main "$@"
