export const FOLDER_TOOL_REQUIREMENT_SCOPES = [
  'nodes:details',
  'nodes:folders:manage',
  'databases:view',
  'databases:folders:manage',
  'domains:view',
  'domains:folders:manage',
  'logs:environments:view',
  'logs:environments:folders:manage',
  'logs:schemas:view',
  'logs:schemas:folders:manage',
  'logs:manage',
  'admin:users',
  'admin:users:folders:manage',
  'admin:groups',
  'admin:groups:folders:manage',
  'proxy:view',
  'proxy:folders:manage',
  'docker:containers:view',
  'docker:images:view',
  'docker:networks:view',
  'docker:volumes:view',
  'docker:containers:folders:manage',
] as const;
