import type { AIToolDefinition } from './ai.types.js';

const connectorIdSchema = {
  type: 'string',
  pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
  description: 'Exact GitLab connector UUID returned by gitlab_list_connectors.',
};

const projectSelector = {
  connectorId: connectorIdSchema,
  project: {
    type: 'string',
    description: 'Synced GitLab project remote ID or full path, for example group/subgroup/repo.',
  },
};

export const GITLAB_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'gitlab_list_connectors',
    description: 'List enabled GitLab connectors available through Gateway. Does not expose connector tokens.',
    parameters: { type: 'object', properties: {} },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_projects',
    description: 'List synced GitLab projects for a connector using Gateway allowlist rules.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: projectSelector.connectorId,
        search: { type: 'string', description: 'Optional project name/path filter.' },
        limit: { type: 'number', description: 'Maximum projects to return. Default 25, max 100.' },
      },
      required: ['connectorId'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:projects:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_get_project',
    description: 'Get one synced GitLab project by remote ID or full path.',
    parameters: { type: 'object', properties: projectSelector, required: ['connectorId', 'project'] },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:projects:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_search_projects',
    description: 'Search synced GitLab projects for a connector. Alias of gitlab_list_projects with a required search.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: projectSelector.connectorId,
        search: { type: 'string', description: 'Project name/path filter.' },
        limit: { type: 'number', description: 'Maximum projects to return. Default 25, max 100.' },
      },
      required: ['connectorId', 'search'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:projects:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_repository_tree',
    description: 'List a GitLab repository folder through direct GitLab API. Results are bounded and do not clone.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        path: { type: 'string', description: 'Repository folder path. Empty means root.' },
        ref: { type: 'string', description: 'Branch, tag, or commit SHA. Defaults to project default branch.' },
        limit: { type: 'number', description: 'Maximum entries. Default 100, max 500.' },
      },
      required: ['connectorId', 'project'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:repo:read',
    invalidateStores: [],
  },
  {
    name: 'gitlab_read_file',
    description:
      'Read a bounded GitLab file chunk through direct API. Use offset/length for large files. Does not clone.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        path: { type: 'string', description: 'Repository file path.' },
        ref: { type: 'string', description: 'Branch, tag, or commit SHA.' },
        offset: { type: 'number', description: 'Byte offset. Default 0.' },
        length: { type: 'number', description: 'Maximum bytes. Default 64 KB, max 256 KB.' },
      },
      required: ['connectorId', 'project', 'path'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:repo:read',
    invalidateStores: [],
  },
  {
    name: 'gitlab_commit_files',
    description:
      'Commit file create/update/delete/move actions directly to GitLab. Direct commits to protected/default branches require explicit approval and GitLab PAT permission.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        branch: { type: 'string', description: 'Target branch.' },
        startBranch: { type: 'string', description: 'Optional source branch when creating a branch.' },
        commitMessage: { type: 'string', description: 'Commit message.' },
        changes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              action: { type: 'string', enum: ['create', 'update', 'delete', 'move'] },
              path: { type: 'string' },
              previousPath: { type: 'string' },
              content: { type: 'string' },
              encoding: { type: 'string', enum: ['text', 'base64'] },
            },
            required: ['action', 'path'],
          },
        },
      },
      required: ['connectorId', 'project', 'branch', 'commitMessage', 'changes'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:repo:write',
    invalidateStores: [],
  },
  {
    name: 'gitlab_lint_ci_config',
    description:
      'Lint GitLab CI YAML through GitLab CI lint. Returns validity, errors, warnings, and merged YAML if available.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, content: { type: 'string', description: 'Proposed .gitlab-ci.yml content.' } },
      required: ['connectorId', 'project', 'content'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_update_ci_config',
    description:
      'Lint and commit .gitlab-ci.yml directly. Invalid CI config is not committed. Requires CI edit permission and approval.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        branch: { type: 'string' },
        startBranch: { type: 'string' },
        content: { type: 'string' },
        commitMessage: { type: 'string' },
      },
      required: ['connectorId', 'project', 'branch', 'content', 'commitMessage'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:edit',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_pipelines',
    description: 'List GitLab pipelines for a project. Bounded result.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, ref: { type: 'string' }, limit: { type: 'number' } },
      required: ['connectorId', 'project'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_get_pipeline',
    description: 'Get one GitLab pipeline by ID.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, pipelineId: { type: 'number' } },
      required: ['connectorId', 'project', 'pipelineId'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_get_pipeline_jobs',
    description: 'List jobs for a GitLab pipeline.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, pipelineId: { type: 'number' }, limit: { type: 'number' } },
      required: ['connectorId', 'project', 'pipelineId'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_get_job_log',
    description: 'Read a bounded GitLab CI job trace. Large logs are capped.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, jobId: { type: 'number' }, limitBytes: { type: 'number' } },
      required: ['connectorId', 'project', 'jobId'],
    },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:ci:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_project_variables',
    description: 'List GitLab project variable metadata only. Values are never returned.',
    parameters: { type: 'object', properties: projectSelector, required: ['connectorId', 'project'] },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:variables:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_set_project_variable',
    description:
      'Create or update one GitLab project variable. The submitted value is secret input and is never returned or stored in audit/model output.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        key: { type: 'string' },
        value: { type: 'string' },
        variableType: { type: 'string', enum: ['env_var', 'file'] },
        protected: { type: 'boolean' },
        masked: { type: 'boolean' },
        raw: { type: 'boolean' },
        environmentScope: { type: 'string' },
        description: { type: 'string' },
      },
      required: ['connectorId', 'project', 'key', 'value'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:variables:edit',
    invalidateStores: [],
  },
  {
    name: 'gitlab_delete_project_variable',
    description: 'Delete one GitLab project variable. This always requires explicit approval.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, key: { type: 'string' }, environmentScope: { type: 'string' } },
      required: ['connectorId', 'project', 'key'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:variables:delete',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_project_webhooks',
    description: 'List GitLab project webhook metadata. Secret tokens are never returned.',
    parameters: { type: 'object', properties: projectSelector, required: ['connectorId', 'project'] },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:webhooks:manage',
    invalidateStores: [],
  },
  {
    name: 'gitlab_create_or_update_project_webhook',
    description: 'Create or update a GitLab project webhook. Secret token input is never returned.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        id: { type: 'number' },
        url: { type: 'string' },
        token: { type: 'string' },
        pushEvents: { type: 'boolean' },
        mergeRequestsEvents: { type: 'boolean' },
        tagPushEvents: { type: 'boolean' },
        jobEvents: { type: 'boolean' },
        pipelineEvents: { type: 'boolean' },
        enableSslVerification: { type: 'boolean' },
      },
      required: ['connectorId', 'project', 'url'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:webhooks:manage',
    invalidateStores: [],
  },
  {
    name: 'gitlab_delete_project_webhook',
    description: 'Delete a GitLab project webhook.',
    parameters: {
      type: 'object',
      properties: { ...projectSelector, hookId: { type: 'number' } },
      required: ['connectorId', 'project', 'hookId'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:webhooks:manage',
    invalidateStores: [],
  },
  {
    name: 'gitlab_list_registry_repositories',
    description: 'List GitLab container registry repositories for a project.',
    parameters: { type: 'object', properties: projectSelector, required: ['connectorId', 'project'] },
    destructive: false,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:registry:view',
    invalidateStores: [],
  },
  {
    name: 'gitlab_create_deploy_token',
    description:
      'Create a GitLab deploy token and store the raw token encrypted inside Gateway. The raw token is never returned; only masked metadata is returned.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        name: { type: 'string' },
        scopes: { type: 'array', items: { type: 'string', enum: ['read_registry', 'write_registry'] } },
        expiresAt: { type: 'string', description: 'Optional YYYY-MM-DD expiry.' },
        registryUrl: { type: 'string', description: 'Optional registry URL binding metadata.' },
      },
      required: ['connectorId', 'project', 'name', 'scopes'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:registry:manage',
    invalidateStores: [],
  },
  {
    name: 'gitlab_clone_repository_to_sandbox',
    description:
      'Download a GitLab repository archive through Gateway, upload it into a no-network sandbox, and extract it under /workspace. No PAT or deploy token is exposed in command text, output, or tool result.',
    parameters: {
      type: 'object',
      properties: {
        ...projectSelector,
        ref: { type: 'string', description: 'Branch, tag, or commit SHA.' },
        targetPath: { type: 'string', description: 'Relative path under /workspace. Defaults to repository name.' },
        ttlSeconds: { type: 'number', description: 'Sandbox TTL. Clamped by sandbox policy.' },
      },
      required: ['connectorId', 'project'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:sandbox:clone',
    invalidateStores: [],
  },
];
