// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: gateway/v1/nginx-daemon.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeEnrollment_Enroll_FullMethodName           = "/gateway.v1.NodeEnrollment/Enroll"
	NodeEnrollment_RenewCertificate_FullMethodName = "/gateway.v1.NodeEnrollment/RenewCertificate"
)

// NodeEnrollmentClient is the client API for NodeEnrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeEnrollmentClient interface {
	// Initial enrollment: daemon presents PSK token, receives mTLS certs
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Certificate renewal: daemon presents current cert, gets new one
	RenewCertificate(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
}

type nodeEnrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeEnrollmentClient(cc grpc.ClientConnInterface) NodeEnrollmentClient {
	return &nodeEnrollmentClient{cc}
}

func (c *nodeEnrollmentClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeEnrollment_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeEnrollmentClient) RenewCertificate(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, NodeEnrollment_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeEnrollmentServer is the server API for NodeEnrollment service.
// All implementations must embed UnimplementedNodeEnrollmentServer
// for forward compatibility.
type NodeEnrollmentServer interface {
	// Initial enrollment: daemon presents PSK token, receives mTLS certs
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// Certificate renewal: daemon presents current cert, gets new one
	RenewCertificate(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	mustEmbedUnimplementedNodeEnrollmentServer()
}

// UnimplementedNodeEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeEnrollmentServer struct{}

func (UnimplementedNodeEnrollmentServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedNodeEnrollmentServer) RenewCertificate(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedNodeEnrollmentServer) mustEmbedUnimplementedNodeEnrollmentServer() {}
func (UnimplementedNodeEnrollmentServer) testEmbeddedByValue()                        {}

// UnsafeNodeEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeEnrollmentServer will
// result in compilation errors.
type UnsafeNodeEnrollmentServer interface {
	mustEmbedUnimplementedNodeEnrollmentServer()
}

func RegisterNodeEnrollmentServer(s grpc.ServiceRegistrar, srv NodeEnrollmentServer) {
	// If the following call panics, it indicates UnimplementedNodeEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeEnrollment_ServiceDesc, srv)
}

func _NodeEnrollment_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeEnrollmentServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeEnrollment_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeEnrollmentServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeEnrollment_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeEnrollmentServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeEnrollment_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeEnrollmentServer).RenewCertificate(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeEnrollment_ServiceDesc is the grpc.ServiceDesc for NodeEnrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeEnrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.NodeEnrollment",
	HandlerType: (*NodeEnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _NodeEnrollment_Enroll_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _NodeEnrollment_RenewCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/nginx-daemon.proto",
}

const (
	NodeControl_CommandStream_FullMethodName = "/gateway.v1.NodeControl/CommandStream"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlClient interface {
	// Bidirectional stream: daemon connects, Gateway pushes commands
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, GatewayCommand], error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, GatewayCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[0], NodeControl_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonMessage, GatewayCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_CommandStreamClient = grpc.BidiStreamingClient[DaemonMessage, GatewayCommand]

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
type NodeControlServer interface {
	// Bidirectional stream: daemon connects, Gateway pushes commands
	CommandStream(grpc.BidiStreamingServer[DaemonMessage, GatewayCommand]) error
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) CommandStream(grpc.BidiStreamingServer[DaemonMessage, GatewayCommand]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServer).CommandStream(&grpc.GenericServerStream[DaemonMessage, GatewayCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_CommandStreamServer = grpc.BidiStreamingServer[DaemonMessage, GatewayCommand]

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _NodeControl_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/v1/nginx-daemon.proto",
}

const (
	LogStream_StreamLogs_FullMethodName = "/gateway.v1.LogStream/StreamLogs"
)

// LogStreamClient is the client API for LogStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogStreamClient interface {
	// Daemon streams log entries to Gateway
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamMessage, LogStreamControl], error)
}

type logStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamClient(cc grpc.ClientConnInterface) LogStreamClient {
	return &logStreamClient{cc}
}

func (c *logStreamClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogStreamMessage, LogStreamControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStream_ServiceDesc.Streams[0], LogStream_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogStreamMessage, LogStreamControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStream_StreamLogsClient = grpc.BidiStreamingClient[LogStreamMessage, LogStreamControl]

// LogStreamServer is the server API for LogStream service.
// All implementations must embed UnimplementedLogStreamServer
// for forward compatibility.
type LogStreamServer interface {
	// Daemon streams log entries to Gateway
	StreamLogs(grpc.BidiStreamingServer[LogStreamMessage, LogStreamControl]) error
	mustEmbedUnimplementedLogStreamServer()
}

// UnimplementedLogStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStreamServer struct{}

func (UnimplementedLogStreamServer) StreamLogs(grpc.BidiStreamingServer[LogStreamMessage, LogStreamControl]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogStreamServer) mustEmbedUnimplementedLogStreamServer() {}
func (UnimplementedLogStreamServer) testEmbeddedByValue()                   {}

// UnsafeLogStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStreamServer will
// result in compilation errors.
type UnsafeLogStreamServer interface {
	mustEmbedUnimplementedLogStreamServer()
}

func RegisterLogStreamServer(s grpc.ServiceRegistrar, srv LogStreamServer) {
	// If the following call panics, it indicates UnimplementedLogStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStream_ServiceDesc, srv)
}

func _LogStream_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogStreamServer).StreamLogs(&grpc.GenericServerStream[LogStreamMessage, LogStreamControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStream_StreamLogsServer = grpc.BidiStreamingServer[LogStreamMessage, LogStreamControl]

// LogStream_ServiceDesc is the grpc.ServiceDesc for LogStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.LogStream",
	HandlerType: (*LogStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogStream_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/v1/nginx-daemon.proto",
}
