/** The scope that grants access to the AI assistant — must match backend canUseAI() */
export const AI_SCOPE = "feat:ai:use" as const;

export const RESOURCE_SCOPABLE_SCOPES = [
  "pki:ca:create:intermediate",
  "pki:cert:view",
  "pki:cert:issue",
  "pki:cert:revoke",
  "pki:cert:export",
  "proxy:view",
  "proxy:create",
  "proxy:edit",
  "proxy:delete",
  "proxy:advanced",
  "proxy:advanced:bypass",
  "proxy:raw:read",
  "proxy:raw:write",
  "proxy:raw:toggle",
  "proxy:raw:bypass",
  "proxy:templates:view",
  "proxy:templates:edit",
  "proxy:templates:delete",
  "ssl:cert:view",
  "ssl:cert:delete",
  "ssl:cert:revoke",
  "ssl:cert:export",
  "acl:view",
  "acl:edit",
  "acl:delete",
  "nodes:details",
  "nodes:config:view",
  "nodes:config:edit",
  "nodes:logs",
  "nodes:console",
  "nodes:files:read",
  "nodes:files:write",
  "nodes:rename",
  "nodes:delete",
  "nodes:lock",
  "nodes:folders:manage",
  "docker:containers:view",
  "docker:containers:create",
  "docker:containers:edit",
  "docker:containers:config",
  "docker:containers:manage",
  "docker:containers:environment",
  "docker:containers:delete",
  "docker:containers:console",
  "docker:containers:files",
  "docker:containers:secrets",
  "docker:containers:webhooks",
  "docker:containers:mounts",
  "docker:images:view",
  "docker:images:pull",
  "docker:images:delete",
  "docker:volumes:view",
  "docker:volumes:create",
  "docker:volumes:delete",
  "docker:volumes:files:read",
  "docker:volumes:files:write",
  "docker:networks:view",
  "docker:networks:create",
  "docker:networks:edit",
  "docker:networks:delete",
  "docker:tasks",
  "docker:tasks:manage",
  "databases:view",
  "databases:edit",
  "databases:delete",
  "databases:query:read",
  "databases:query:write",
  "databases:query:admin",
  "databases:credentials:reveal",
  "databases:folders:manage",
  "logs:environments:view",
  "logs:environments:edit",
  "logs:environments:delete",
  "logs:tokens:view",
  "logs:tokens:create",
  "logs:tokens:delete",
  "logs:schemas:view",
  "logs:schemas:edit",
  "logs:schemas:delete",
  "logs:read",
] as const;

// API Token / Group scopes
const RAW_TOKEN_SCOPES = [
  // PKI: Certificate Authorities
  {
    value: "pki:ca:view:root",
    label: "View Root CAs",
    desc: "View root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:view:intermediate",
    label: "View Intermediate CAs",
    desc: "View intermediate certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:create:root",
    label: "Create Root CAs",
    desc: "Create new root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:create:intermediate",
    label: "Create Intermediate CAs",
    desc: "Create intermediate CAs under a root",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:revoke:root",
    label: "Revoke Root CAs",
    desc: "Revoke root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:revoke:intermediate",
    label: "Revoke Intermediate CAs",
    desc: "Revoke intermediate certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  // PKI: Certificates
  {
    value: "pki:cert:view",
    label: "View Certificates",
    desc: "View issued certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:issue",
    label: "Issue Certificates",
    desc: "Issue new certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:revoke",
    label: "Revoke Certificates",
    desc: "Revoke issued certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:export",
    label: "Export Certificates",
    desc: "Export certificates and keys",
    group: "PKI: Certificates",
  },
  // PKI: Templates
  {
    value: "pki:templates:view",
    label: "View Templates",
    desc: "View certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:create",
    label: "Create Templates",
    desc: "Create certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:edit",
    label: "Edit Templates",
    desc: "Edit certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:delete",
    label: "Delete Templates",
    desc: "Delete certificate templates",
    group: "PKI: Templates",
  },
  // Domains
  { value: "domains:view", label: "View Domains", desc: "View managed domains", group: "Domains" },
  {
    value: "domains:create",
    label: "Create Domains",
    desc: "Create managed domains",
    group: "Domains",
  },
  { value: "domains:edit", label: "Edit Domains", desc: "Edit managed domains", group: "Domains" },
  {
    value: "domains:delete",
    label: "Delete Domains",
    desc: "Delete managed domains",
    group: "Domains",
  },
  {
    value: "domains:folders:manage",
    label: "Manage Domain Folders",
    desc: "Organize managed domains into folders",
    group: "Domains",
  },
  // Proxy Hosts
  {
    value: "proxy:view",
    label: "View Proxy Hosts",
    desc: "View and search proxy hosts",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:create",
    label: "Create Proxy Hosts",
    desc: "Create new proxy hosts",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:edit",
    label: "Edit Proxy Hosts",
    desc: "Edit proxy host configuration",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:delete",
    label: "Delete Proxy Hosts",
    desc: "Delete proxy hosts",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:advanced",
    label: "Advanced Proxy Config",
    desc: "Use advanced proxy configuration",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:advanced:bypass",
    label: "Bypass Advanced Config Restrictions",
    desc: "Save unrestricted advanced nginx snippets",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:raw:read",
    label: "Read Raw Config",
    desc: "View raw nginx configuration",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:raw:write",
    label: "Write Raw Config",
    desc: "Edit raw nginx configuration",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:raw:toggle",
    label: "Toggle Raw Config",
    desc: "Switch between managed and raw config mode",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:raw:bypass",
    label: "Bypass Raw Config Restrictions",
    desc: "Save raw nginx config without dangerous directive restrictions",
    group: "Proxy Hosts",
  },
  {
    value: "proxy:folders:manage",
    label: "Manage Proxy Folders",
    desc: "Create, reorder, and remove proxy host folders",
    group: "Proxy Hosts",
  },
  // Proxy Templates
  {
    value: "proxy:templates:view",
    label: "View Nginx Templates",
    desc: "View nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:create",
    label: "Create Nginx Templates",
    desc: "Create nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:edit",
    label: "Edit Nginx Templates",
    desc: "Edit nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:delete",
    label: "Delete Nginx Templates",
    desc: "Delete nginx templates",
    group: "Proxy Templates",
  },
  // SSL Certificates
  {
    value: "ssl:cert:view",
    label: "View SSL Certificates",
    desc: "View SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:issue",
    label: "Issue SSL Certificates",
    desc: "Provision ACME or upload SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:delete",
    label: "Delete SSL Certificates",
    desc: "Delete SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:revoke",
    label: "Revoke SSL Certificates",
    desc: "Revoke SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:export",
    label: "Export SSL Certificates",
    desc: "Export SSL certificates",
    group: "SSL Certificates",
  },
  // Access Control Lists
  {
    value: "acl:view",
    label: "View Access Lists",
    desc: "View access control lists",
    group: "Access Control",
  },
  {
    value: "acl:create",
    label: "Create Access Lists",
    desc: "Create access control lists",
    group: "Access Control",
  },
  {
    value: "acl:edit",
    label: "Edit Access Lists",
    desc: "Edit access control lists",
    group: "Access Control",
  },
  {
    value: "acl:delete",
    label: "Delete Access Lists",
    desc: "Delete access control lists",
    group: "Access Control",
  },
  // Nodes
  { value: "nodes:details", label: "View Nodes", desc: "View managed nodes", group: "Nodes" },
  { value: "nodes:create", label: "Create Nodes", desc: "Enroll new nodes", group: "Nodes" },
  { value: "nodes:rename", label: "Rename Nodes", desc: "Rename nodes", group: "Nodes" },
  { value: "nodes:delete", label: "Delete Nodes", desc: "Remove nodes", group: "Nodes" },
  {
    value: "nodes:lock",
    label: "Lock Service Creation",
    desc: "Prevent new proxy hosts or containers on selected nodes",
    group: "Nodes",
  },
  {
    value: "nodes:config:view",
    label: "View Node Config",
    desc: "View node nginx configuration",
    group: "Nodes",
  },
  {
    value: "nodes:config:edit",
    label: "Edit Node Config",
    desc: "Edit node nginx configuration",
    group: "Nodes",
  },
  {
    value: "nodes:logs",
    label: "View Node Logs",
    desc: "View node daemon and nginx logs",
    group: "Nodes",
  },
  {
    value: "nodes:console",
    label: "Node Console",
    desc: "Open interactive shell on nodes",
    group: "Nodes",
  },
  {
    value: "nodes:files:read",
    label: "Read Node Files",
    desc: "Browse, open, copy, and download node files",
    group: "Nodes",
  },
  {
    value: "nodes:files:write",
    label: "Write Node Files",
    desc: "Create, edit, upload, move, and delete node files",
    group: "Nodes",
  },
  {
    value: "nodes:folders:manage",
    label: "Manage Node Folders",
    desc: "Create, reorder, and remove node folders",
    group: "Nodes",
  },
  // Administration
  {
    value: "admin:users",
    label: "Manage Users",
    desc: "Create, edit, and delete users",
    group: "Administration",
  },
  {
    value: "admin:users:folders:manage",
    label: "Manage User Folders",
    desc: "Create, reorder, and remove user folders",
    group: "Administration",
  },
  {
    value: "admin:groups",
    label: "Manage Groups",
    desc: "Create, edit, and delete permission groups",
    group: "Administration",
  },
  {
    value: "admin:groups:folders:manage",
    label: "Manage Group Folders",
    desc: "Create, reorder, and remove permission group folders",
    group: "Administration",
  },
  {
    value: "admin:audit",
    label: "View Audit Log",
    desc: "View the audit log",
    group: "Administration",
  },
  {
    value: "admin:system",
    label: "System Admin",
    desc: "System-level administration (protected)",
    group: "Administration",
  },
  {
    value: "admin:details:certificates",
    label: "View System Certificates",
    desc: "View internal system PKI and SSL certificates in read-only mode",
    group: "Administration",
  },
  {
    value: "admin:update",
    label: "Manage Updates",
    desc: "Check for and apply updates",
    group: "Administration",
  },
  {
    value: "admin:alerts",
    label: "Manage Alerts",
    desc: "View and manage alerts",
    group: "Administration",
  },
  // Gateway Settings
  {
    value: "settings:gateway:view",
    label: "View Gateway Settings",
    desc: "View sign-in provisioning and external control-plane settings",
    group: "Gateway Settings",
  },
  {
    value: "settings:gateway:edit",
    label: "Edit Gateway Settings",
    desc: "Edit sign-in provisioning and external control-plane settings",
    group: "Gateway Settings",
  },
  // Housekeeping
  {
    value: "housekeeping:view",
    label: "View Housekeeping",
    desc: "View housekeeping configuration, stats, and run history",
    group: "Housekeeping",
  },
  {
    value: "housekeeping:run",
    label: "Run Housekeeping",
    desc: "Manually run housekeeping tasks",
    group: "Housekeeping",
  },
  {
    value: "housekeeping:configure",
    label: "Configure Housekeeping",
    desc: "Edit housekeeping configuration and schedule",
    group: "Housekeeping",
  },
  // Licensing
  {
    value: "license:view",
    label: "View License",
    desc: "View Gateway license status and entitlement details",
    group: "Licensing",
  },
  {
    value: "license:manage",
    label: "Manage License",
    desc: "Activate, update, or remove the Gateway license",
    group: "Licensing",
  },
  // Notifications
  {
    value: "notifications:alerts:view",
    label: "View Alert Rules",
    desc: "View notification alert rules",
    group: "Notifications",
  },
  {
    value: "notifications:alerts:create",
    label: "Create Alert Rules",
    desc: "Create notification alert rules",
    group: "Notifications",
  },
  {
    value: "notifications:alerts:edit",
    label: "Edit Alert Rules",
    desc: "Edit notification alert rules",
    group: "Notifications",
  },
  {
    value: "notifications:alerts:delete",
    label: "Delete Alert Rules",
    desc: "Delete notification alert rules",
    group: "Notifications",
  },
  {
    value: "notifications:webhooks:view",
    label: "View Webhooks",
    desc: "View notification webhooks",
    group: "Notifications",
  },
  {
    value: "notifications:webhooks:create",
    label: "Create Webhooks",
    desc: "Create notification webhooks",
    group: "Notifications",
  },
  {
    value: "notifications:webhooks:edit",
    label: "Edit Webhooks",
    desc: "Edit notification webhooks",
    group: "Notifications",
  },
  {
    value: "notifications:webhooks:delete",
    label: "Delete Webhooks",
    desc: "Delete notification webhooks",
    group: "Notifications",
  },
  {
    value: "notifications:deliveries:view",
    label: "View Delivery Logs",
    desc: "View webhook delivery attempts",
    group: "Notifications",
  },
  {
    value: "notifications:view",
    label: "View Notifications",
    desc: "Read notification resources across alerts, webhooks, and deliveries",
    group: "Notifications",
  },
  {
    value: "notifications:manage",
    label: "Manage Notifications",
    desc: "Full management access to alerts, webhooks, and deliveries",
    group: "Notifications",
  },
  // Status Page
  {
    value: "status-page:view",
    label: "View Status Page",
    desc: "View status page configuration, exposed services, incidents, and preview",
    group: "Status Page",
  },
  {
    value: "status-page:manage",
    label: "Manage Status Page",
    desc: "Edit status page settings and exposed services",
    group: "Status Page",
  },
  {
    value: "status-page:incidents:create",
    label: "Create Incidents",
    desc: "Create manual incidents and promote automatic incidents",
    group: "Status Page",
  },
  {
    value: "status-page:incidents:update",
    label: "Update Incidents",
    desc: "Edit incident details and post incident timeline updates",
    group: "Status Page",
  },
  {
    value: "status-page:incidents:resolve",
    label: "Resolve Incidents",
    desc: "Resolve active status page incidents",
    group: "Status Page",
  },
  {
    value: "status-page:incidents:delete",
    label: "Delete Past Incidents",
    desc: "Delete resolved status page incidents",
    group: "Status Page",
  },
  // Features
  {
    value: "feat:ai:use",
    label: "Use AI Assistant",
    desc: "Use the AI assistant",
    group: "Features",
  },
  {
    value: "feat:ai:configure",
    label: "Configure AI",
    desc: "Configure AI settings and providers",
    group: "Features",
  },
  {
    value: "ai:sandbox:use",
    label: "Use Sandbox Runner",
    desc: "Run bounded AI sandbox jobs",
    group: "Features",
  },
  {
    value: "ai:sandbox:tier:medium",
    label: "Use Medium Sandbox Tier",
    desc: "Run AI sandbox jobs with medium resource limits",
    group: "Features",
  },
  {
    value: "ai:sandbox:tier:high",
    label: "Use High Sandbox Tier",
    desc: "Run AI sandbox jobs with high resource limits",
    group: "Features",
  },
  {
    value: "ai:sandbox:manage",
    label: "Manage Sandbox Jobs",
    desc: "View and kill AI sandbox jobs",
    group: "Features",
  },
  {
    value: "mcp:use",
    label: "Use MCP",
    desc: "Allow this user account to access the remote MCP server with OAuth",
    group: "Features",
  },
  // Docker: Containers
  {
    value: "docker:containers:view",
    label: "View Containers",
    desc: "View Docker containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:create",
    label: "Create Containers",
    desc: "Create and duplicate containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:edit",
    label: "Edit Containers",
    desc: "Edit container settings and configuration",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:config",
    label: "Container Config",
    desc: "View container recreate/configuration fields",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:manage",
    label: "Manage Containers",
    desc: "Start, stop, restart, kill, and recreate containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:environment",
    label: "Container Environment",
    desc: "Modify container environment variables",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:delete",
    label: "Delete Containers",
    desc: "Remove containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:console",
    label: "Container Console",
    desc: "Open interactive console in containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:files",
    label: "Container Files",
    desc: "Browse and edit files in containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:secrets",
    label: "Container Secrets",
    desc: "View and manage encrypted secrets",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:webhooks",
    label: "Container Webhooks",
    desc: "View and manage container webhook update triggers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:mounts",
    label: "Container Mounts",
    desc: "Add, remove, or change container and deployment mounts",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:folders:manage",
    label: "Manage Container Folders",
    desc: "Create, reorder, and remove Docker container folders",
    group: "Docker: Containers",
  },
  // Docker: Images
  {
    value: "docker:images:view",
    label: "View Images",
    desc: "View Docker images",
    group: "Docker: Images",
  },
  {
    value: "docker:images:pull",
    label: "Pull Images",
    desc: "Pull Docker images",
    group: "Docker: Images",
  },
  {
    value: "docker:images:delete",
    label: "Delete Images",
    desc: "Remove and prune Docker images",
    group: "Docker: Images",
  },
  // Docker: Volumes
  {
    value: "docker:volumes:view",
    label: "View Volumes",
    desc: "View Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:create",
    label: "Create Volumes",
    desc: "Create Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:delete",
    label: "Delete Volumes",
    desc: "Remove Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:files:read",
    label: "Read Volume Files",
    desc: "Browse, open, and download Docker volume files",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:files:write",
    label: "Write Volume Files",
    desc: "Create, edit, upload, move, and delete Docker volume files",
    group: "Docker: Volumes",
  },
  // Docker: Networks
  {
    value: "docker:networks:view",
    label: "View Networks",
    desc: "View Docker networks",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:create",
    label: "Create Networks",
    desc: "Create Docker networks",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:edit",
    label: "Edit Networks",
    desc: "Connect and disconnect containers",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:delete",
    label: "Delete Networks",
    desc: "Remove Docker networks",
    group: "Docker: Networks",
  },
  // Docker: Registries
  {
    value: "docker:registries:view",
    label: "View Registries",
    desc: "View Docker registries",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:create",
    label: "Create Registries",
    desc: "Add Docker registries",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:edit",
    label: "Edit Registries",
    desc: "Edit Docker registry settings",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:delete",
    label: "Delete Registries",
    desc: "Remove Docker registries",
    group: "Docker: Registries",
  },
  // Docker: Tasks
  {
    value: "docker:tasks",
    label: "View Tasks",
    desc: "View Docker task progress",
    group: "Docker: Tasks",
  },
  {
    value: "docker:tasks:manage",
    label: "Manage Tasks",
    desc: "Force-cancel active Docker tasks",
    group: "Docker: Tasks",
  },
  // Databases
  {
    value: "databases:view",
    label: "View Databases",
    desc: "View saved database connections",
    group: "Databases",
  },
  {
    value: "databases:create",
    label: "Create Databases",
    desc: "Create saved database connections",
    group: "Databases",
  },
  {
    value: "databases:edit",
    label: "Edit Databases",
    desc: "Edit saved database connections",
    group: "Databases",
  },
  {
    value: "databases:delete",
    label: "Delete Databases",
    desc: "Delete saved database connections",
    group: "Databases",
  },
  {
    value: "databases:query:read",
    label: "Read Database Data",
    desc: "Browse tables, keys, and run read-only database queries",
    group: "Databases",
  },
  {
    value: "databases:query:write",
    label: "Write Database Data",
    desc: "Insert, update, delete, and run write queries against databases",
    group: "Databases",
  },
  {
    value: "databases:query:admin",
    label: "Admin Database Queries",
    desc: "Run administrative or DDL database commands",
    group: "Databases",
  },
  {
    value: "databases:credentials:reveal",
    label: "Reveal Database Credentials",
    desc: "Reveal saved database credentials and connection strings",
    group: "Databases",
  },
  {
    value: "databases:folders:manage",
    label: "Manage Database Folders",
    desc: "Create, reorder, and remove database folders",
    group: "Databases",
  },
  {
    value: "logs:environments:view",
    label: "View Logging Environments",
    desc: "View external logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:create",
    label: "Create Logging Environments",
    desc: "Create logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:edit",
    label: "Edit Logging Environments",
    desc: "Edit logging environments and schemas",
    group: "Logging",
  },
  {
    value: "logs:environments:delete",
    label: "Delete Logging Environments",
    desc: "Delete logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:folders:manage",
    label: "Manage Logging Environment Folders",
    desc: "Create, reorder, and remove logging environment folders",
    group: "Logging",
  },
  {
    value: "logs:tokens:view",
    label: "View Logging Tokens",
    desc: "View logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:tokens:create",
    label: "Create Logging Tokens",
    desc: "Create logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:tokens:delete",
    label: "Delete Logging Tokens",
    desc: "Revoke logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:schemas:view",
    label: "View Logging Schemas",
    desc: "View reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:create",
    label: "Create Logging Schemas",
    desc: "Create reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:edit",
    label: "Edit Logging Schemas",
    desc: "Edit reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:delete",
    label: "Delete Logging Schemas",
    desc: "Delete reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:folders:manage",
    label: "Manage Logging Schema Folders",
    desc: "Create, reorder, and remove logging schema folders",
    group: "Logging",
  },
  {
    value: "logs:read",
    label: "Read Logs",
    desc: "Search and inspect external logs",
    group: "Logging",
  },
  {
    value: "logs:manage",
    label: "Manage Logging",
    desc: "Full access to external logging",
    group: "Logging",
  },
] as const;

export const TOKEN_SCOPES = RAW_TOKEN_SCOPES;

const PROGRAMMATIC_DENIED_SCOPE_VALUES = new Set<string>([
  "feat:ai:use",
  "feat:ai:configure",
  "ai:sandbox:use",
  "ai:sandbox:tier:medium",
  "ai:sandbox:tier:high",
  "ai:sandbox:manage",
  "mcp:use",
  "admin:system",
  "admin:users",
  "admin:groups",
  "settings:gateway:view",
  "settings:gateway:edit",
  "proxy:raw:read",
  "proxy:raw:write",
  "proxy:raw:toggle",
  "proxy:raw:bypass",
  "proxy:advanced:bypass",
  "nodes:config:view",
  "nodes:config:edit",
]);

export const API_TOKEN_SCOPES = TOKEN_SCOPES.filter(
  (scope) => !PROGRAMMATIC_DENIED_SCOPE_VALUES.has(scope.value)
);

export const GROUP_ASSIGNABLE_SCOPES = TOKEN_SCOPES.filter(
  (scope) => scope.value !== "admin:system"
);
